### ISSUE TITLE
Kang not loading properly

### ISSUE THREAD

**Issue by jossives** [twistedsistem/OCTGN-Marvel-Champions#38]
The following happens when I try to load Kang, before or after adding my hero, in Standard or Expert and with the default modular or other. And after close and re-opening the program.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\anon\AppData\Local\Programs\OCTGN\Data\GameDatabase\055c536f-adba-4bc2-acbf-9aefb9756046\scripts\loadVillain.py", line 157, in loadVillain
  File "C:\Users\anon\AppData\Local\Programs\OCTGN\Data\GameDatabase\055c536f-adba-4bc2-acbf-9aefb9756046\scripts\actions.py", line 318, in tableSetup
  File "C:\Users\anon\AppData\Local\Programs\OCTGN\Data\GameDatabase\055c536f-adba-4bc2-acbf-9aefb9756046\scripts\loadVillain.py", line 242, in villainSetup
  File "C:\Users\anon\AppData\Local\Programs\OCTGN\Data\GameDatabase\055c536f-adba-4bc2-acbf-9aefb9756046\scripts\loadVillain.py", line 260, in SpecificVillainSetup
IndexError: index out of range: 0

result = loadVillain(table, 55.814, 19.767)

**Comment by Ouroboros009** [comment]
Uploaded new update to fix this issue. Thanks for opening this.
